### ISSUE TITLE
[Feature Request] test 1 frrfr ping idfk

### ISSUE THREAD

**Issue by ExlyYT** [Iris-Interactive-Group/Kurogami-Scripting-Bugs#2]
![image](https://github.com/user-attachments/assets/d6db52de-50bb-4320-b9f2-ea16651ae817)

**Comment by AzuuuDev** [comment]
Idk this shit broken or sum

**Comment by AzuuuDev** [comment]
Test again ig?

**Comment by lordgoosey** [comment]
goose 🪿
