### ISSUE TITLE
[BUG] Uncrouching when you are not supposed to be able

### ISSUE THREAD

**Issue by ExlyYT** [Iris-Interactive-Group/Kurogami-Scripting-Bugs#6]
**Describe the bug**
You can uncrouch even tho u have no space and ur required to crouch
**To Reproduce**
go crouch In the tunnel and uncrouch

**Expected behavior**
When you try to uncrouch nothing happens

**Screenshots**
it's literally that simple
**Platform**
Desktop
**Additional context**

**Comment by AzuuuDev** [comment]
This issue has been resolved now
