### ISSUE TITLE
[BUG] Sliding while running then walking removes the walk anim

### ISSUE THREAD

**Issue by ExlyYT** [Iris-Interactive-Group/Kurogami-Scripting-Bugs#7]
**Describe the bug**
When you go to slide and you stop and then start holding W mid-slide removes your walking animation

**To Reproduce**
  1. Start Running
2. Slide
3. Stop running mid-slide
4. Start walking mid-slide

**Expected behavior**
The walk animation should play instead of not at all, until you reset your movement
**Screenshots**
![image](https://github.com/user-attachments/assets/26b03791-93ba-4d78-9dd0-e98d503df94e)

**Platform**
Desktop
**Additional context**

**Comment by ExlyYT** [comment]
its not only with the w key

**Comment by AzuuuDev** [comment]
Tested this and it works fine now!
